### PR TITLE
support of emt (Elapsed Move Time) command in pgn comments

### PR DESCRIPTION
**Pull request by aipv**
Elapsed Move Time in the pgn file #836. A simple pull request follows the implementation of clock() and set_clock() function, please feel free the modify it if it can be better. thank you.

### CODE REVIEW

**Comment by niklasf** [comment]
Thanks! Will also need some tests in `test.py`.

**Comment by aipv** [comment]
Thank you very much for the comments and sorry for missing the test codes. The pull request is updated to include the "emt" comment in test_annotations(), and an individual test case in test_float_emt(). When set_emt() to a negative value, it sets the Elapsed Move Time to 0:00:00, similar as the set_clock(), I think it makes sensor and hope it is ok.  Please let me know if further test cases are required, thank you very much!

**Comment by niklasf** [comment]
Perfect. If you or anyone else wants to use this before the next release
```sh
pip install git+https://github.com/niklasf/python-chess.git
```
would work.

**Comment by aipv** [comment]
Yes, it works. thank you very much!

**Pull request merged**
