### PR TITLE
Updated unicode representation of the chess board

### PR DESCRIPTION
**Pull request by FaiqIftikhar**
Now the chessboard representation is:
```
♜ ♞ ♝ ♛ ♚ ♝ ♞ ♜
♟ ♟ ♟ ♟ ♟ ♟ ♟ ♟
⭘ ⭘ ⭘ ⭘ ⭘ ⭘ ⭘ ⭘
⭘ ⭘ ⭘ ⭘ ⭘ ⭘ ⭘ ⭘
⭘ ⭘ ⭘ ⭘ ⭘ ⭘ ⭘ ⭘
⭘ ⭘ ⭘ ⭘ ⭘ ⭘ ⭘ ⭘
♙ ♙ ♙ ♙ ♙ ♙ ♙ ♙
♖ ♘ ♗ ♕ ♔ ♗ ♘ ♖
```

### CODE REVIEW

**Comment by PedanticHacker** [comment]
Since we dropped Python 2 support, I think the u”.” (or u”[]” if Niklas merges this pull request) should only be “.” (or “[]”), i.e., without the letter ‘u’, since all strings in Python 3 are now inherently Unicode.

**Comment by PedanticHacker** [comment]
I don't think Niklas is going to merge this. The pieces relative to empty squares are not aligned properly. If you look closely, there's a distinct shift, not visually pleasing at all. I think the interpoint `·` looks best.

**Comment by niklasf** [comment]
Sorry, can't review right now, because my terminal font does not support this character.

**Comment by FaiqIftikhar** [comment]
This character is not supported in android font-face. Most people use this on Windows/Linux in which this is not an issue. [Link to a similar issue](https://stackoverflow.com/questions/11982136/unicode-symbols-not-displaying-correctly-in-mobile-devices)

**Comment by PedanticHacker** [comment]
If we are going to switch the interpoint for some other Unicode character, at least choose one that is square-shaped. Squares are not round. :)

**Comment by FaiqIftikhar** [comment]
Unfortunately, there's no right sized square Unicode that aligns with the size of pieces. I tried multiple:
```
♜ ♞ ♝ ♛ ♚ ♝ ♞ ♜
♟ ♟ ♟ ♟ ♟ ♟ ♟ ♟
☐ ☐ ☐ ☐ ☐ ☐ ☐ ☐
☐ ☐ ☐ ☐ ☐ ☐ ☐ ☐
☐ ☐ ☐ ☐ ☐ ☐ ☐ ☐
☐ ☐ ☐ ☐ ☐ ☐ ☐ ☐
♙ ♙ ♙ ♙ ♙ ♙ ♙ ♙
♖ ♘ ♗ ♕ ♔ ♗ ♘ ♖
```

**Comment by PedanticHacker** [comment]
Me and Niklas had the same problem a while back. There was a simple period character before (and I didn't like it). He then switched it for the interpoint and made things much better. I think it's best the way it is with the interpoint. Don't fix what ain't broken, ey? ;)

**Comment by niklasf** [comment]
@FaiqIftikhar Could you please share a screenshot?

**Comment by FaiqIftikhar** [comment]
Here is the screenshot of the board, I used it to log stuff, [Screenshot](https://imgur.com/RrLlL0o)

**Comment by PedanticHacker** [comment]
I’ve done some testing. I have access to 4 different devices:
(1) iPhone 8 running on iOS 13.3.1 (the latest official [non-beta] version from Apple).
(2) Huawei P30 Pro on official Android/EMUI 10 with all of its apps updated to today.
(3) Lenovo laptop running on Manjaro Linux, KDE Plasma, version 19.0.2 (all patches installed to today).
(4) Acer laptop running on Windows 10 version 1909 (the latest official version from Microsoft including all installed patches to today).

Here are my findings:
(1) The iPhone 8 displays the board properly aligned in Safari web browser and also in Chrome web browser.
(2) The Huawei P30 Pro does not display the board properly aligned in Chrome web browser.
(3) Lenovo laptop does not display the board properly aligned in Chromium web browser.
(4) The Acer laptop displays the board properly aligned in Firefox web browser.

So, you see, it all depends on which operating system you’re on. The iOS is okay and Windows 10 are okay. Android and Linux are the bad apples here.

Again, I would not advise to switch the interpoint character for some other. Currently, the board is properly aligned on all aforementioned operating systems having the interpoint character. We’ll just have to live with it.

**Comment by FaiqIftikhar** [comment]
Thank you @PedanticHacker, it is a problem in Linux. :)

**Comment by PedanticHacker** [comment]
Is there any site we can report this Unicode rendering bug for Linux?

I don’t know whether this bug is lurking in the Linux kernel itself or in its distributions.

**Comment by PedanticHacker** [comment]
I am testing this further on **_Linux_** and I am observing that in _**Chromium**_, the Unicode characters appear horizontally **shrunk** as opposed to pieces on the board representation; whereas in **_Firefox_**, they are horizontally **stretched** past the _h_ file. Anyone else observes the same?

**Comment by niklasf** [comment]
There is no bug. It just depends on the font, and if it supports this character.

**Pull request closed without merging**
