### PR TITLE
Grammar fixes

### PR DESCRIPTION
**Pull request by PedanticHacker**
Fixed some grammar. It was missed at my last review.

### CODE REVIEW

**Comment by niklasf** [comment]
Thanks!

**Comment by PedanticHacker** [comment]
When are you planning to release a new version? It's highly anticipated. 🙂

**Comment by niklasf** [comment]
Before the next release I need to find some time to finish #390. Currently the type signatures are half-broken.

**Comment by PedanticHacker** [comment]
In chess/engine.py line 56 there is this line of code:
`InfoDict = NewType("InfoDict", Dict[str, Union[str, int, float, bool, "PovScore", List[chess.Move], Dict[chess.Move, List[chess.Move]]]])`

This is spaghetti code. Maybe Mypy has trouble type-checking this?

**Pull request merged**
