### PR TITLE
Improve class Arrow in chess.svg

### PR DESCRIPTION
**Pull request by PedanticHacker**
A subclass of `collections.namedtuple` must implement the `__slots__`
attribute and, in this case, an empty tuple must be assigned to it.

### CODE REVIEW

**Comment by niklasf** [comment]
Thanks, I wasn't aware of this. Can you please explain? Is this required for correctness, is it an optimization?

**Comment by PedanticHacker** [comment]
I read the Python documentation regarding collections.namedtuple. It is expressed there that when subclassing collections.namedtuple, the __slots__ = () is needed because "this helps keep memory requirements low by preventing the creation of instance dictionaries".

**Comment by niklasf** [comment]
Cool. Maybe avoiding the subclassing is even better, since nothing is added anyway?

**Comment by PedanticHacker** [comment]
I agree. Just remove this `Arrow` subclass object altogether and add `Arrow = collections.namedtuple("Arrow", ["tail", "head"])` somewhere in chess.svg module.

I was wondering why the field names `"tail"` and `"head"` are passed in as a list of strings. `Arrow = collections.namedtuple("Arrow", "tail, head")` does the trick as well. You can even pass them in as `"tail head"`, but I'd go for `"tail, head"` (my personal taste is that with the comma looks better).

**Comment by niklasf** [comment]
Unfortunately this seems to not include the docstring (unless explicitly assigned to `__doc__`). So I'll just go with your first suggestion.

**Pull request merged**
