### PR TITLE
Generalize the LC0 8-move requirement

### PR DESCRIPTION
**Pull request by Mk-Chan**
Pretty trivial change I think

### CODE REVIEW

**Comment by Mk-Chan** [comment]
Something just failed for seemingly no reason...
https://travis-ci.org/niklasf/python-chess/jobs/382288829#L1847

**Comment by Mk-Chan** [comment]
Ok, looking seriously at this, https://syzygy-tables.info/gaviota is 404. My entire Travis CI test suite failed because of this: https://travis-ci.org/Mk-Chan/python-chess/jobs/382287956

I don't think this is python-chess' fault but it may be cause for concern for the test suite if this 404 is permanent.

**Comment by Mk-Chan** [comment]
I suppose it's not specified by UCI but neither is the lc0 requirement. In fact UCI defines a position as the initial fen + all moves following. I think this option also provides a way to achieve that (by giving it the total stack size as the argument).

The default could be changed for the convenience of lc0 sure... But that seems a bit partial. Although I'm not against supporting the latest innovation in computer chess, I'm not so sure ethically choosing 8 as default is fine.

Either way, it's your choice. If I were to go with the lc0 requirement I'd prefer being able to get however many moves I want back (since lc0 is still in development)

**Comment by niklasf** [comment]
You can convinced me that hardcoding a value that's useful specifically for a single engine is not ideal (even if it does not significantly hurt other engines).

But instead of making this configurable, I'll try to fix the underlying performance issue and always send all moves. In the meantime I'll still release the status-quo, together with some bugfixes.

**Comment by Mk-Chan** [comment]
So what exactly is the performance issue? Can we not just store a list of all strings and just print " ".join(list) it?

**Comment by niklasf** [comment]
Yes, that will be the goal. Currently all moves have to be replayed to retrieve the initial FEN and normalize notation of castling moves.

**Comment by niklasf** [comment]
Now sending the full history again, but more efficiently. Via: 9fd2d3e7e5619e306cc5cf0c64971ec6619f95bc, ae48918d21a923a153f00e49b01d726343de9a94 and 446280c1174a8c57ed5ed4dc8df92c92e5755a2a.

**Pull request closed without merging**
