### PR TITLE
Introduce restore_position() method in chess.Board()

### PR DESCRIPTION
**Pull request by PedanticHacker**
Introduced a new method in chess.Board() named restore_position() that restores the chessboard to a position by passing it an integer value as the index argument.

### CODE REVIEW

**Comment by PedanticHacker** [comment]
@niklasf, is my implementation correct?

**Comment by niklasf** [comment]
There's still a test or type checking failure, but it's definitely better than your previous approach. Mostly because the result no longer has an inconsistent history.

But that's because it does not have any history. Was that really your intention?

I think what you said in https://github.com/PedanticHacker/ChessFighter/issues/14#issuecomment-705752307 is a better idea. Just use `copy()`. You don't need `restore()` when you can just assign a different object to `board_state`.

**Comment by PedanticHacker** [comment]
@niklasf, why does the `copy()` method of `chess.Board()` not include the following?

```
self.turn = board.turn
self.castling_rights = board.castling_rights
self.ep_square = board.ep_square
self.halfmove_clock = board.halfmove_clock
self.fullmove_number = board.fullmove_number
```

**Comment by niklasf** [comment]
https://github.com/niklasf/python-chess/blob/ec90b9b7cfc8ed3b4aa08824e86c643beaa723cb/chess/__init__.py#L3498-L3502

**Pull request closed without merging**
