### PR TITLE
Fix spelling error and introduce Stockfish 11 instead of Stockfish 10

### PR DESCRIPTION
**Pull request by TesseractA**
As the title comments; hopefully I've not neglected anything that has "Stockfish 10" in it.

### CODE REVIEW

**Comment by TesseractA** [comment]
Fixes #541 and my conscience about spelling errors

**Comment by niklasf** [comment]
Thanks. Can you please update Stockfish `.travis.yml` as well?

**Comment by PedanticHacker** [comment]
I think it doesn't hurt if we use stockfish_20011801_x64_bmi2.exe. The BMI2 version is much much faster. Intel processors since 2013 (basically from the Haswell processor design onwards) all use this new instruction set. The BMI2 instruction set (i.e., the pext and pdep instructions) makes it possible to speed up Stockfish calculations quite a bit, actually.

**Comment by TesseractA** [comment]
@PedanticHacker How about AMD processors? (Also, my desktop is a 2011 computer, yes outdated, but probably cannot run bmi2)

**Comment by TesseractA** [comment]
Well I'm not installing stockfish with pychess anytime soon. But from my perspective it looks like this one is done.

**Comment by niklasf** [comment]
Thanks!

This is just the automated test suite, so performance doesn't really matter. Both modern or bmi2 are fine, if the testing infracstructure supports it.

**Comment by brianprichardson** [comment]
If including SF here then certainly the lowest common denominator version should be used.  Many have PCs without BMI2 support (some even without popcnt).  Python-chess should not be triggering problems with SF which is not part of this repo, IMHO.  If you want to leave it as is fine.  If it triggers a bunch of "python-chess does not work for me anymore" issues it is easy to see if this is the cause and revert at that point.

**Comment by TesseractA** [comment]
Well, what we could do is test whether stockfish installs and runs. If not, then we can create an assert that causes us to install another version.

**Pull request merged**
