### PR TITLE
Added parse_square function: #624

### PR DESCRIPTION
**Pull request by tanmay2004**

### CODE REVIEW

**Comment by niklasf** [comment]
Thanks. I think it would be better to raise `ValueError` if this fails. Like https://github.com/niklasf/python-chess/blob/1e6353792df58b31c264ae3cfe8277ea8d579fb1/chess/__init__.py#L490.

**Comment by tanmay2004** [comment]
If we used `.index` instead of `.find` as I have done, then it would automatically raise a `ValueError`. Is that what you mean?

**Comment by tanmay2004** [comment]
@niklasf I'm confused, do you mean I should just return as I am right now, but with `.index`? Or should I use a try and catch and raise the `ValueError` with a custom message?

**Comment by tanmay2004** [comment]
Wait, if @PedanticHacker made another pull request with the same changes, what should I do? Sorry, but I'm fairly new to contributing on Github.

**Comment by PedanticHacker** [comment]
Don't worry, I just made the function a little bit tidy and I used the index() function so that a ValueError is raised if the function fails. Kudos are all to you, @tanmay2004! ;)

**Comment by tanmay2004** [comment]
Thanks! Actually, I had just edited my branch with the `.index` change and was gonna commit it when I saw your pull request. So, I'm a bit confused....

**Comment by niklasf** [comment]
Thank you, both.

**Pull request merged**
