### PR TITLE
draw knights moves using right-angled arrows

### PR DESCRIPTION
**Pull request by tewhalen**
Because I am a beginner at chess, it's easier for me to understand what's going on when arrows depicting a knight's move are drawn using right angles. I whipped up a patch that does this (and because I am not very good at math, I off-loaded some of the calculations onto the svg renderer). See attached image.
Screen Shot 2020-12-13 at 4 38 55 PM

### CODE REVIEW

**Comment by niklasf** [comment]
Thanks for the pull request. The rendered result looks pretty good. A couple of comments:

* Please don't make changes to the coding style of the surrounding lines. It makes it hard to spot the actual changes. Instead, adjust your own additions to the surrounding coding style.
* I like the right-angled style, but I don't think it should be default. Arrows by `(2, 1)` are not guaranteed to be knight moves, semantically. Instead, `shape` or `style` could be a property of `Arrow`, similar to `color`.
* The transforms appear to be SVG Tiny compatible. We should double check that, though.

**Comment by sshivaji** [comment]
Wanted to point out that the bishop move is incorrect, it's not diagonal in
the diagram. Am sure this is probably minor.

**Comment by tewhalen** [comment]
> Wanted to point out that the bishop move is incorrect, it's not diagonal in the diagram. Am sure this is probably minor.

Yeah, that's a D5 -> G3 arrow, not intended to indicate a bishop's move.

>     * Please don't make changes to the coding style of the surrounding lines. It makes it hard to spot the actual changes. Instead, adjust your own additions to the surrounding coding style.

Sorry about that – the perils of relying on `black` for formatting help.

>     * I like the right-angled style, but I don't think it should be default. Arrows by `(2, 1)` are not guaranteed to be knight moves, semantically. Instead, `shape` or `style` could be a property of `Arrow`, similar to `color`.

That makes sense. I'll see if I can revise to make the arrow style selectable. I'm still learning the ins and outs of SVG, so I made the whole arrow (line + head) a polygon, which perhaps is not the right move, since it will be harder to style. I'll see about switching the lines back to lines or polylines and making the arrow head a marker.

>     * The transforms appear to be SVG Tiny compatible. We should double check that, though.

Hrrrm, I wasn't aware that was the target - I'll see if I can find a validator and check the output.

**Comment by niklasf** [comment]
Sounds good. I don't mind the line/polygon decision. Whichever is easier to implement.

**Comment by PedanticHacker** [comment]
Although the idea of this PR is very interesting, the implementation of it is very bad.

Here's my rant about it:
`(1)` Unnecessary code style changes, as @niklasf 
already pointed out (and a very bad style proposed, if you ask me); `(2)` no type annotations (that's why there were errors); `(3)` neglecting PEP 8 completely, especially with comments (a comment should start start with a capital letter, and end with a dot); `(4)` you don't gain anything by prepending two underscores to a function (one underscore is enough).

I propose this PR is deleted, and a new attempt is made.

**Comment by tewhalen** [comment]
> Although the idea of this PR is very interesting, the implementation of it is very bad.

I'll poke around with it a little more. I learned Python before PEP 8 was written and I haven't programmed professionally in over 15 years, so my style is pretty bad by modern standards.

**Comment by PedanticHacker** [comment]
I noticed that Fritz chess GUI does not have L-shaped knight move arrows. So I think it's fine not having that. I guess there's no need for this.

**Pull request closed without merging**
